// app.js — frontend logic: collect the profile, call the AI function, render results.

const form = document.getElementById("profile-form");
const formScreen = document.getElementById("form-screen");
const loading = document.getElementById("loading");
const errorBox = document.getElementById("error");
const errorText = document.getElementById("error-text");
const resultsScreen = document.getElementById("results-screen");

const sourceBadge = document.getElementById("source-badge");
const resultsSummary = document.getElementById("results-summary");
const benefitsList = document.getElementById("benefits-list");
const documentsList = document.getElementById("documents-list");
const nextStep = document.getElementById("next-step");

// Human-readable labels so the AI gets clear text instead of raw codes.
const LABELS = {
  loneStatus: {
    lone_from_israel: "Lone soldier from Israel (no supporting family in Israel)",
    lone_immigrant: "Lone soldier who is a new immigrant (oleh chadash)",
    not_sure: "Not sure if recognized as a lone soldier",
    no: "Not a lone soldier",
  },
  serviceType: {
    combat: "Combat role",
    combat_support: "Combat support role",
    non_combat: "Non-combat role",
  },
  serviceLength: {
    "0-6m": "Less than 6 months of service",
    "6-12m": "6 to 12 months of service",
    "12m+": "More than a year of service",
    released: "Recently released from service",
  },
  housing: {
    rent_alone: "Renting an apartment alone",
    rent_shared: "Renting with roommates",
    adoptive_family: "Living with an adoptive family",
    dorm: "Living in army dorm / base housing",
    other: "Other housing situation",
  },
};

function show(el) {
  el.classList.remove("hidden");
}
function hide(el) {
  el.classList.add("hidden");
}

function buildProfile(formData) {
  return {
    loneStatus: LABELS.loneStatus[formData.get("loneStatus")] || "Unknown",
    serviceType: LABELS.serviceType[formData.get("serviceType")] || "Unknown",
    serviceLength: LABELS.serviceLength[formData.get("serviceLength")] || "Unknown",
    housing: LABELS.housing[formData.get("housing")] || "Unknown",
    notes: (formData.get("notes") || "").trim(),
  };
}

form.addEventListener("submit", async (e) => {
  e.preventDefault();
  const profile = buildProfile(new FormData(form));

  hide(formScreen);
  hide(errorBox);
  hide(resultsScreen);
  show(loading);

  try {
    const res = await fetch("/.netlify/functions/ai", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ profile }),
    });

    if (!res.ok) throw new Error("Server responded with status " + res.status);

    const data = await res.json();
    renderResults(data);
    hide(loading);
    show(resultsScreen);
  } catch (err) {
    console.error(err);
    hide(loading);
    errorText.textContent =
      "Sorry, something went wrong while checking your benefits. Please try again.";
    show(errorBox);
  }
});

function renderResults(data) {
  // Source badge: was this a real AI answer or the offline fallback?
  sourceBadge.className = "badge " + (data.source === "ai" ? "ai" : "fallback");
  sourceBadge.textContent =
    data.source === "ai"
      ? "Generated by AI"
      : "Offline estimate (AI unavailable)";
  show(sourceBadge);

  resultsSummary.textContent = data.summary || "Here is what we found for you:";

  benefitsList.innerHTML = "";
  (data.benefits || []).forEach((b) => {
    const li = document.createElement("li");
    const title = document.createElement("span");
    title.className = "b-title";
    title.textContent = b.name || "Benefit";
    const why = document.createElement("span");
    why.className = "b-why";
    why.textContent = b.why || "";
    li.appendChild(title);
    li.appendChild(why);
    benefitsList.appendChild(li);
  });

  documentsList.innerHTML = "";
  (data.documents || []).forEach((d) => {
    const li = document.createElement("li");
    li.textContent = d;
    documentsList.appendChild(li);
  });

  nextStep.textContent = data.nextStep || "Contact your unit's welfare officer (mashakit tash).";
}

// reset / retry buttons
document.getElementById("restart-btn").addEventListener("click", () => {
  hide(resultsScreen);
  show(formScreen);
});
document.getElementById("retry-btn").addEventListener("click", () => {
  hide(errorBox);
  show(formScreen);
});
